FIREBASE_APP_ID = ENV["FIREBASE_APP_ID"]
FIREBASE_TOKEN = ENV["FIREBASE_TOKEN"]

default_platform(:android)
platform :android do
  desc "Builds App & uploads to Firebase App Distribution"
  lane :build_firebase do
      firebase_app_distribution(
          app: "#{FIREBASE_APP_ID}",
          firebase_cli_token: "#{FIREBASE_TOKEN}",
          firebase_cli_path: "/usr/local/bin/firebase",
          apk_path: "../build/app/outputs/apk/release/app-release.apk"
      )
  end
end
