name: Build Android to Firebase

on:
  push:
    branches:
    - "main"
jobs:
  build_to_firebase:
    name: Deploy Android build to Firebase App Distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: 3.0.1
      - run: flutter pub get
      - run: flutter format --set-exit-if-changed .
      - run: flutter analyze .
      - run: flutter test
      - run: flutter build apk
      - name: Run Fastlane
        uses: maierj/fastlane-action@v2.0.1
        with:
          lane: build_firebase
          subdirectory: android
          bundle-install-path: "~/vendor/bundle"
        env:
          FIREBASE_APP_ID: "${{ secrets.FIREBASE_APP_ID }}"
          FIREBASE_TOKEN: "${{ secrets.FIREBASE_TOKEN }}"